CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "name" varchar,
  "gender" varchar,
  "birthdate" date,
  "password" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "icks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ick" text,
  "registered_by" int default 0,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_icks" (
  "user_id" int,
  "icks_id" int,
  PRIMARY KEY ("user_id", "icks_id")
);

ALTER TABLE "user_icks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_icks" ADD FOREIGN KEY ("icks_id") REFERENCES "icks" ("id");

ALTER TABLE "icks" ADD FOREIGN KEY ("registered_by") REFERENCES "users" ("id");
